sudo: true
dist: xenial

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    # CPython 3.6
    - python: 3.6
      env: TOXENV=py36-local
      stage: Client Tests
    # we don't have any yet
    #- python: 3.6
    #  env: TOXENV=py36-integ
    #  stage: Client Tests
    # we don't have any yet
    #- python: 3.6
    #  env: TOXENV=py36-examples
    #  stage: Client Tests
    # CPython 3.7
    - python: 3.7
      env: TOXENV=py37-local
      stage: Client Tests
    # we don't have any yet
    #- python: 3.7
    #  env: TOXENV=py37-integ
    #  stage: Client Tests
    # we don't have any yet
    #- python: 3.7
    #  env: TOXENV=py37-examples
    #  stage: Client Tests
    # Security
    - python: 3.7
      env: TOXENV=bandit
      stage: Static Checks
    # Linting
    # disable for now
    #- python: 3.7
    #  env: TOXENV=lint
    #  stage: Static Checks
    # MyPy
    # disable for now
    #- python: 3.7
    #  env: TOXENV=mypy-py3
    #  stage: Static Checks

install: pip install tox
script: tox -- -vv
